name = "dev03"
type = "javascript"
account_id = "ef0034d5b5a3e9838c877e31094e3251"
workers_dev = true

[site]
bucket = "./out"

[build]
command = "npm run build"
upload.format = "service-worker"

pages_build_output_dir = "./out"
