name = "dev03"
type = "javascript"
account_id = "ef0034d5b5a3e9838c877e31094e3251"
workers_dev = true

[site]
bucket = "./out" # This should be the directory where Next.js outputs its static files after build

[build]
command = "npm run build && npm run export" # Ensures the project builds and exports correctly

[env.production]
pages_build_output_dir = "./out" # Ensure this matches the output directory specified above
