name = "dev03"
type = "javascript"
account_id = "ef0034d5b5a3e9838c877e31094e3251"  # Your account ID from Cloudflare
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./.next"

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

[env.production]
pages_build_output_dir = ".next"